[build.environment]
FOOTER = "FOOTER "
GRAPH_LINK_REPLACE = "y"
GRAPH_OPTIONS = """
        {
        	nodes: {
        		shape: "dot",
        		color: isDark() ? "#8c8e91" : "#dee2e6",
        		font: {
        			face: "Inter",
        			color: isDark() ? "#c9cdd1" : "#616469",
        			strokeColor: isDark() ? "#c9cdd1" : "#616469",
        		},
        		scaling: {
        			label: {
        				enabled: true,
        			},
        		},
        	},
        	edges: {
        		color: { inherit: "both" },
        		width: 0.8,
        		smooth: {
        			type: "continuous",
        		},
        		hoverWidth: 4,
        	},
        	interaction: {
        		hover: true,
        	},
        	height: "100%",
        	width: "100%",
        	physics: {
        		solver: "repulsion",
        	},
        }
        """
HOME_GRAPH = "y"
LANDING_BUTTON = "<span class='shake-rotate shake-freeze'>Click to Enter</span>"
LANDING_DESCRIPTION = "<div style='margin-bottom: 1rem; margin-top: -3rem;'>My physical brain is <div style='font-size: 4rem; display: inline-block' class='animate__animated animate__pulse animate__infinite '>💤 </div> but my digital brain is active.</div>"
LANDING_PAGE = "home"
LANDING_TITLE = "<span class='hvr-grow'>Hi, I'm Kevin</span>"
LOCAL_GRAPH = "y"
PAGE_GRAPH = "y"
PYTHON_VERSION = "3.8"
REPO_URL = "https://github.com/avatar333/thegarden"
ROOT_SECTION_NAME = "root"
SITE_TITLE = "The Garden 42"
SITE_TITLE_TAB = "The Garden 42"
SITE_URL = "https://thegarden42.netlify.app/"
SLUGIFY = "y"
STRICT_LINE_BREAKS = "y"
TIMEZONE = "Africa/Johannesburg"
ZOLA_VERSION = "0.15.2"
